
export const STATECODES = {
  "Federal": "Federal",
  "Military": "Military",
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
  }
  
  
  export const STATEOPTIONS = [
    { key: 'Federal', value: 'Federal', text: 'Federal', image: { src: "/images/flags/mini-res/usa.png" } },
    { key: 'Military', value: 'Military', text: 'Military', image: { src: "/images/flags/mini-res/military.png" } },
    { key: 'AL', value: 'AL', text: 'Alabama', image: { src: "/images/flags/mini-res/al.png" } },
    { key: 'AK', value: 'AK', text: 'Alaska', image: { src: "/images/flags/mini-res/ak.png" } },
    { key: 'AZ', value: 'AZ', text: 'Arizona', image: { src: "/images/flags/mini-res/az.png" } },
    { key: 'AR', value: 'AR', text: 'Arkansas', image: { src: "/images/flags/mini-res/ar.png" } },
    { key: 'CA', value: 'CA', text: 'California', image: { src: "/images/flags/mini-res/ca.png" } },
    { key: 'CO', value: 'CO', text: 'Colorado', image: { src: "/images/flags/mini-res/co.png" } },
    { key: 'CT', value: 'CT', text: 'Connecticut', image: { src: "/images/flags/mini-res/ct.png" } },
    { key: 'DE', value: 'DE', text: 'Delaware', image: { src: "/images/flags/mini-res/de.png" } },
    { key: 'FL', value: 'FL', text: 'Florida', image: { src: "/images/flags/mini-res/fl.png" } },
    { key: 'GA', value: 'GA', text: 'Georgia', image: { src: "/images/flags/mini-res/ga.png" } },
    { key: 'HI', value: 'HI', text: 'Hawaii', image: { src: "/images/flags/mini-res/hi.png" } },
    { key: 'ID', value: 'ID', text: 'Idaho', image: { src: "/images/flags/mini-res/id.png" } },
    { key: 'IL', value: 'IL', text: 'Illinois', image: { src: "/images/flags/mini-res/il.png" } },
    { key: 'IN', value: 'IN', text: 'Indiana', image: { src: "/images/flags/mini-res/in.png" } },
    { key: 'IA', value: 'IA', text: 'Iowa', image: { src: "/images/flags/mini-res/ia.png" } },
    { key: 'KS', value: 'KS', text: 'Kansas', image: { src: "/images/flags/mini-res/ks.png" } },
    { key: 'KY', value: 'KY', text: 'Kentucky', image: { src: "/images/flags/mini-res/ky.png" } },
    { key: 'LA', value: 'LA', text: 'Louisiana', image: { src: "/images/flags/mini-res/la.png" } },
    { key: 'ME', value: 'ME', text: 'Maine', image: { src: "/images/flags/mini-res/me.png" } },
    { key: 'MD', value: 'MD', text: 'Maryland', image: { src: "/images/flags/mini-res/md.png" } },
    { key: 'MA', value: 'MA', text: 'Massachusetts', image: { src: "/images/flags/mini-res/ma.png" } },
    { key: 'MI', value: 'MI', text: 'Michigan', image: { src: "/images/flags/mini-res/mi.png" } },
    { key: 'MN', value: 'MN', text: 'Minnesota', image: { src: "/images/flags/mini-res/mn.png" } },
    { key: 'MS', value: 'MS', text: 'Mississippi', image: { src: "/images/flags/mini-res/ms.png" } },
    { key: 'MO', value: 'MO', text: 'Missouri', image: { src: "/images/flags/mini-res/mo.png" } },
    { key: 'MT', value: 'MT', text: 'Montana', image: { src: "/images/flags/mini-res/mt.png" } },
    { key: 'NE', value: 'NE', text: 'Nebraska', image: { src: "/images/flags/mini-res/ne.png" } },
    { key: 'NV', value: 'NV', text: 'Nevada', image: { src: "/images/flags/mini-res/nv.png" } },
    { key: 'NH', value: 'NH', text: 'New Hampshire', image: { src: "/images/flags/mini-res/nh.png" } },
    { key: 'NJ', value: 'NJ', text: 'New Jersey', image: { src: "/images/flags/mini-res/nj.png" } },
    { key: 'NM', value: 'NM', text: 'New Mexico', image: { src: "/images/flags/mini-res/nm.png" } },
    { key: 'NY', value: 'NY', text: 'New York', image: { src: "/images/flags/mini-res/ny.png" } },
    { key: 'NC', value: 'NC', text: 'North Carolina', image: { src: "/images/flags/mini-res/nc.png" } },
    { key: 'ND', value: 'ND', text: 'North Dakota', image: { src: "/images/flags/mini-res/nd.png" } },
    { key: 'OH', value: 'OH', text: 'Ohio', image: { src: "/images/flags/mini-res/oh.png" } },
    { key: 'OK', value: 'OK', text: 'Oklahoma', image: { src: "/images/flags/mini-res/ok.png" } },
    { key: 'OR', value: 'OR', text: 'Oregon', image: { src: "/images/flags/mini-res/or.png" } },
    { key: 'PA', value: 'PA', text: 'Pennsylvania', image: { src: "/images/flags/mini-res/pa.png" } },
    { key: 'RI', value: 'RI', text: 'Rhode Island', image: { src: "/images/flags/mini-res/ri.png" } },
    { key: 'SC', value: 'SC', text: 'South Carolina', image: { src: "/images/flags/mini-res/sc.png" } },
    { key: 'SD', value: 'SD', text: 'South Dakota', image: { src: "/images/flags/mini-res/sd.png" } },
    { key: 'TN', value: 'TN', text: 'Tennessee', image: { src: "/images/flags/mini-res/tn.png" } },
    { key: 'TX', value: 'TX', text: 'Texas', image: { src: "/images/flags/mini-res/tx.png" } },
    { key: 'UT', value: 'UT', text: 'Utah', image: { src: "/images/flags/mini-res/ut.png" } },
    { key: 'VT', value: 'VT', text: 'Vermont', image: { src: "/images/flags/mini-res/vt.png" } },
    { key: 'VA', value: 'VA', text: 'Virginia', image: { src: "/images/flags/mini-res/va.png" } },
    { key: 'WA', value: 'WA', text: 'Washington', image: { src: "/images/flags/mini-res/wa.png" } },
    { key: 'WV', value: 'WV', text: 'West Virginia', image: { src: "/images/flags/mini-res/wv.png" } },
    { key: 'WI', value: 'WI', text: 'Wisconsin', image: { src: "/images/flags/mini-res/wi.png" } },
    { key: 'WY', value: 'WY', text: 'Wyoming', image: { src: "/images/flags/mini-res/wy.png" } }
  ]
